export const INVALID_ARRAY_ARGUMENT = 'Argument is not an array';
export const INVALID_ARRAY_FIRST_ARGUMENT = 'First argument is not an array';
export const INVALID_ARRAY_SECOND_ARGUMENT = 'Second argument is not an array';
export const INVALID_STRING_ARGUMENT = 'Argument is not a string';
export const INVALID_FUNCTION_ARGUMENT = 'Argument is not a function';
export const INVALID_NUMBER_ARGUMENT = 'Argument is not a number';
export const INVALID_DATE = 'Argument must be a valid date';
export const INVALID_DATES = 'Arguments must be a valid dates';
export const INVALID_TIME_UNIT = 'A valid time unit is expected';
